# Generated by Django 3.0.8 on 2020-08-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Id for user auditor'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Id for user customer'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingClass', verbose_name='Id for class of meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingType', verbose_name='Id for type of meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.MeetingState', verbose_name='ID for state of meeting'),
        ),
    ]
