# Generated by Django 3.0.8 on 2020-08-06 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20200806_0200'),
        ('reports_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='system',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.SystemType'),
        ),
        migrations.AddField(
            model_name='report',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='attacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.AttackType'),
        ),
        migrations.AddField(
            model_name='report',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.Meeting'),
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.ReportState'),
        ),
        migrations.AddField(
            model_name='report',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.System'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.Complexity'),
        ),
    ]
