# Generated by Django 3.0.7 on 2020-08-09 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_auto_20200809_0445'),
        ('reports_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-Customer table'),
        ),
        migrations.AddField(
            model_name='system',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.SystemType', verbose_name='Foreign key of SystemType table'),
        ),
        migrations.AddField(
            model_name='report',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis', to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-analyst Table'),
        ),
        migrations.AddField(
            model_name='report',
            name='attacks',
            field=models.ManyToManyField(to='reports_management.AttackType', verbose_name='Foreign key of many to many relation with Attacks Table'),
        ),
        migrations.AddField(
            model_name='report',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-auditor Table'),
        ),
        migrations.AddField(
            model_name='report',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='meetings.Meeting', verbose_name='Foreign key of Meeting Table'),
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.ReportState', verbose_name='Foreign key of State Table'),
        ),
        migrations.AddField(
            model_name='report',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.System', verbose_name='Foreign key of System Table'),
        ),
        migrations.AddField(
            model_name='attacktype',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.Complexity', verbose_name='Foreign key of Complexity'),
        ),
    ]
