# Generated by Django 3.0.6 on 2020-08-04 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20200803_2244'),
        ('reports_management', '0002_auto_20200804_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktype',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.Complexity', verbose_name='Foreign key of Complexity'),
        ),
        migrations.AlterField(
            model_name='report',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis', to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-analyst Table'),
        ),
        migrations.AlterField(
            model_name='report',
            name='attacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.AttackType', verbose_name='Foreign key of Attacks Table'),
        ),
        migrations.AlterField(
            model_name='report',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-auditor Table'),
        ),
        migrations.AlterField(
            model_name='report',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meetings.Meeting', verbose_name='Foreign key of Meeting Table'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.ReportState', verbose_name='Foreign key of State Table'),
        ),
        migrations.AlterField(
            model_name='report',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.System', verbose_name='Foreign key of System Table'),
        ),
        migrations.AlterField(
            model_name='system',
            name='OS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.OperatingSystem', verbose_name='Foreing key of Operating System table'),
        ),
        migrations.AlterField(
            model_name='system',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Foreign key of User-Customer table'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports_management.SystemType', verbose_name='Foreign key of SystemType table'),
        ),
    ]
